### ISSUE TITLE
may i have a manual about how to use this plugin

### ISSUE THREAD

**Issue by EnderAvaritia** [Arkaeriit/devzat-extractor#1]
i try to build it and run
![Snipaste_2024-08-09_16-16-13](https://github.com/user-attachments/assets/fa8bc7b6-4b74-4441-b4b5-3c1c03ece594)
it seems work,but
![Snipaste_2024-08-09_16-17-47](https://github.com/user-attachments/assets/d8c8dba9-e4d9-49a3-b7f7-a33b0d65f32f)
i dont know how to use it

**Comment by Arkaeriit** [comment]
It's a normal plugin, here is the Devzat plugin documentation:https://github.com/quackduck/devzat/blob/main/plugin/README.md  
TLDR: on the Devzat instance, if the plugin integration is enabled, an admin should give a plugin token with the `grant` command. 

When invoking the plugin, you should have set the `DEVZAT_HOST` to point to the gRPC port of the Devzat instance and `DEVZAT_TOKEN` should the the token gotten with the `grant` command.

**Comment by EnderAvaritia** [comment]
![Snipaste_2024-08-09_17-56-03](https://github.com/user-attachments/assets/82c56b6e-ff41-4b1a-9bbb-2bd4d73d4231)
![Snipaste_2024-08-09_17-58-43](https://github.com/user-attachments/assets/d3b57344-ad38-41b7-b2d5-596271d7ce42)
![Snipaste_2024-08-09_17-59-15](https://github.com/user-attachments/assets/89da51ea-df23-459f-b0b9-d6a3c067ea3c)
i dont know what is the problem，it dont work ,is there are some fault in my operation

**Comment by EnderAvaritia** [comment]
> ![Snipaste_2024-08-09_17-56-03](https://private-user-images.githubusercontent.com/84321282/356549600-82c56b6e-ff41-4b1a-9bbb-2bd4d73d4231.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTg3MDMsIm5iZiI6MTcyMzE5ODQwMywicGF0aCI6Ii84NDMyMTI4Mi8zNTY1NDk2MDAtODJjNTZiNmUtZmY0MS00YjFhLTliYmItMmJkNGQ3M2Q0MjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDEwMTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5OTNiMmJjNjYwMzk5NWE2YWE2YWRlZWQ4NTA1ZDhkMzQyYTAyOWVmZWU0YmI4MmVjMDk3N2I0MDZjYmE4NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ylRWImGLjTsDkHBqvEIrmVXKHaNxWESG_OqAEOe8I60) ![Snipaste_2024-08-09_17-58-43](https://private-user-images.githubusercontent.com/84321282/356550449-d3b57344-ad38-41b7-b2d5-596271d7ce42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTg3MDMsIm5iZiI6MTcyMzE5ODQwMywicGF0aCI6Ii84NDMyMTI4Mi8zNTY1NTA0NDktZDNiNTczNDQtYWQzOC00MWI3LWIyZDUtNTk2MjcxZDdjZTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDEwMTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3OTk3OGM4NzE2OTE0ZWE4Yjg3ZGFkYWJlZWE5YWVkM2RhZTAyODQ5YmYxZjRiZTE0ZTJmMzZiYWRhOTI5MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sIgjg9Efz6PgkU9FIkCSRDCSHgQQW4NCoKJ6GjyZEQ4) ![Snipaste_2024-08-09_17-59-15](https://private-user-images.githubusercontent.com/84321282/356550546-89da51ea-df23-459f-b0b9-d6a3c067ea3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTg3MDMsIm5iZiI6MTcyMzE5ODQwMywicGF0aCI6Ii84NDMyMTI4Mi8zNTY1NTA1NDYtODlkYTUxZWEtZGYyMy00NTlmLWIwYjktZDZhM2MwNjdlYTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDEwMTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMDVlZWNlYjc1ODljYjgyMWZhZWViODNjZmU5NGFhNWJjODNhMDNjZmNhODM4ZDU5MzczNTZhYWMwZTdmZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xoCfJrjlyEacrCwgtO43THQz7oqVu3t4vfU-8w1gzOk) i dont know what is the problem，it dont work ,is there are some fault in my operation

export DEVZAT_HOST=https://127.0.0.1:5556
something wrong but still not work

**Comment by Arkaeriit** [comment]
Try `export DEVZAT_HOST=127.0.0.1:5556`. The `https://` prefix is breaking it.

**Comment by EnderAvaritia** [comment]
> Try `export DEVZAT_HOST=127.0.0.1:5556`. The `https://` prefix is breaking it.

well another crash
```
No host given, defaulting to http://localhost:2865
No bank size given, defaulting to 1000
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /timespan/:room/:from/:to/extract.txt --> main.main.func3.1 (3 handlers)
[GIN-debug] GET    /timespan-all/:from/:to/extract.txt --> main.main.func3.2 (3 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on localhost:2865
panic: runtime error: index out of range [0] with length 0

goroutine 12 [running]:
main.timestampWhenDuration({0x0?, 0x1010000001d?})
        /home/etc/devzat-extractor/main.go:88 +0x117
main.genExtractedURL({0x0?, 0x10bf740?}, {0x0, 0x0}, 0xc0004592e0, {0xc0001dac18, 0x15})
        /home/etc/devzat-extractor/main.go:123 +0x52
main.main.func2({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, {0xc000504718?, 0x991f54?})
        /home/etc/devzat-extractor/main.go:209 +0x53
github.com/quackduck/devzat/devzatapi.(*Session).RegisterCmd.func1()
        /home/etc/go/gopath/pkg/mod/github.com/quackduck/devzat/devzatapi@v0.0.0-20230802013159-13ed25d25c1c/main.go:192 +0x28b
created by github.com/quackduck/devzat/devzatapi.(*Session).RegisterCmd in goroutine 1
        /home/etc/go/gopath/pkg/mod/github.com/quackduck/devzat/devzatapi@v0.0.0-20230802013159-13ed25d25c1c/main.go:179 +0x1fb
```

**Comment by EnderAvaritia** [comment]
[devzatExtractor.zip](https://github.com/user-attachments/files/16560678/devzatExtractor.zip)

**Comment by EnderAvaritia** [comment]
![Snipaste_2024-08-09_19-59-46](https://github.com/user-attachments/assets/bf990e5b-5248-40fa-a672-18f960166048)
well it works i find another problem 
the `DEVZAT_TOKEN` need a input which is encoded with base64
![Snipaste_2024-08-09_20-02-11](https://github.com/user-attachments/assets/a6ce072c-2906-4e65-8419-1e785b10c18b)

the first token in picture ,instand of the second ,i used the second before

**Comment by Arkaeriit** [comment]
You must copy-paste the granted-token and not the one from `lstoken`. In your case, you need to do `export DEVZAT_TOKEN=dvz@3x...`.

**Comment by EnderAvaritia** [comment]
> You must copy-paste the granted-token and not the one from `lstoken`. In your case, you need to do `export DEVZAT_TOKEN=dvz@3x...`.

it finally solved
can it be added into the manual?

**Comment by Arkaeriit** [comment]
Yep, I will try to improve the readme.

**Comment by EnderAvaritia** [comment]
it works but
![Snipaste_2024-08-09_22-19-22](https://github.com/user-attachments/assets/222b7714-1809-4038-84e8-6565952937e4)
![Snipaste_2024-08-09_22-19-39](https://github.com/user-attachments/assets/7b435759-827e-4527-82b1-fe3af45393a7)
![图片](https://github.com/user-attachments/assets/5ef5609a-1467-45e2-a54c-e6b09878664b)

**Comment by EnderAvaritia** [comment]
it seems the problem in network ,he can get the file from localhost
![图片](https://github.com/user-attachments/assets/097bed68-7f15-46c1-808a-da02f5f448c3)
